-- Importacao de paineis (NR10) a partir do CSV Lista_Unificada_Paineis_NR10_v2_frango.csv
-- Substitua o tenant_id abaixo pelo tenant correto antes de executar.
-- tenant_id: '00000000-0000-0000-0000-000000000000'::uuid

with source as (
  select *
  from (
    values
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PAE01','PAINEL 01 CCM'),
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PAE02','PAINEL 02 CCM'),
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PAE03','PAINEL 03 CCM'),
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PAE05','PAINEL 05 CCM'),
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PEE02','PAINEL ENTRADA DE ENERGIA 02 CCM'),
      ('ABATE','ABA-ESC','ESCALDAGEM','PAE10','PAINEL DE COMANDO ESCALDAGEM'),
      ('ABATE','ABA-EVIS','EVISCERACAO','PAE11','PAINEL DE COMANDO EVISCERACAO'),
      ('ABATE','ABA-LAVGAI','SETOR LAVAGEM DE GAIOLAS','PAE07','PAINEL DAS BOMBAS DE VACUO'),
      ('ABATE','ABA-SATEMP','SALA DE TEMPERO','PAE16','PAINEL DE COMANDO ROSCA DE GELO'),
      ('ABATE','ABA-SEEXT','SETOR EXTERNO','PAE18','PAINEL ELETRICO PARA OS COMPRESSORES N1'),
      ('ABATE','ABA-SEEXT','SETOR EXTERNO','PAE19','PAINEL ELETRICO PARA OS COMPRESSORES N2'),
      ('ABATE','ABA-SEEXT','SETOR EXTERNO','INFRAELE01','INFRAESTRUTURA ELETRICA DO ABATEDOURO'),
      ('SALA DE MAQUINAS','SM-CCM','CENTRO DE CONTROLE DE MOTORES','PESM04','PAINEL ELETRICO CCM N3'),
      ('SALA DE MAQUINAS','SM-CCM','CENTRO DE CONTROLE DE MOTORES','PESM05','PAINEL ELETRICO CCM N2'),
      ('SALA DE MAQUINAS','SM-CCM','CENTRO DE CONTROLE DE MOTORES','PESM06','PAINEL ELETRICO CCM N1'),
      ('SALA DE MAQUINAS','SM-CCM','CENTRO DE CONTROLE DE MOTORES','PESM07','PAINEL ELETRICO CCM N4'),
      ('SALA DE MAQUINAS','SM-TRANS','TRANSFORMADORES DISTRIBUICAO','CABALTE01','CABINE DE ENTRADA ALTA TENSAO'),
      ('GRAXARIA','GRX-GER','GERACAO DE VAPOR','PAE20','PAINEL ELETRICO NA GRAXARIA'),
      ('GRAXARIA','GRX-GER','GERACAO DE VAPOR','PAEGRX','PAINEL ELETRICO NA GRAXARIA')
  ) as t(endereco, local, equipamento, tag_interna, descricao_detalhada)
)
-- 1) cria locais (sites) por endereco + local
insert into public.sites (name, address, tenant_id)
select distinct
  s.local,
  s.endereco,
  '00000000-0000-0000-0000-000000000000'::uuid
from source s
where not exists (
  select 1
  from public.sites si
  where si.tenant_id = '00000000-0000-0000-0000-000000000000'::uuid
    and si.name = s.local
    and coalesce(si.address, '') = s.endereco
);

-- 2) cria equipamentos (assets) vinculando ao local
with source as (
  select *
  from (
    values
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PAE01','PAINEL 01 CCM'),
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PAE02','PAINEL 02 CCM'),
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PAE03','PAINEL 03 CCM'),
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PAE05','PAINEL 05 CCM'),
      ('ABATE','PRE-CCM','CENTRO DE CONTROLE DE MOTORES','PEE02','PAINEL ENTRADA DE ENERGIA 02 CCM'),
      ('ABATE','ABA-ESC','ESCALDAGEM','PAE10','PAINEL DE COMANDO ESCALDAGEM'),
      ('ABATE','ABA-EVIS','EVISCERACAO','PAE11','PAINEL DE COMANDO EVISCERACAO'),
      ('ABATE','ABA-LAVGAI','SETOR LAVAGEM DE GAIOLAS','PAE07','PAINEL DAS BOMBAS DE VACUO'),
      ('ABATE','ABA-SATEMP','SALA DE TEMPERO','PAE16','PAINEL DE COMANDO ROSCA DE GELO'),
      ('ABATE','ABA-SEEXT','SETOR EXTERNO','PAE18','PAINEL ELETRICO PARA OS COMPRESSORES N1'),
      ('ABATE','ABA-SEEXT','SETOR EXTERNO','PAE19','PAINEL ELETRICO PARA OS COMPRESSORES N2'),
      ('ABATE','ABA-SEEXT','SETOR EXTERNO','INFRAELE01','INFRAESTRUTURA ELETRICA DO ABATEDOURO'),
      ('SALA DE MAQUINAS','SM-CCM','CENTRO DE CONTROLE DE MOTORES','PESM04','PAINEL ELETRICO CCM N3'),
      ('SALA DE MAQUINAS','SM-CCM','CENTRO DE CONTROLE DE MOTORES','PESM05','PAINEL ELETRICO CCM N2'),
      ('SALA DE MAQUINAS','SM-CCM','CENTRO DE CONTROLE DE MOTORES','PESM06','PAINEL ELETRICO CCM N1'),
      ('SALA DE MAQUINAS','SM-CCM','CENTRO DE CONTROLE DE MOTORES','PESM07','PAINEL ELETRICO CCM N4'),
      ('SALA DE MAQUINAS','SM-TRANS','TRANSFORMADORES DISTRIBUICAO','CABALTE01','CABINE DE ENTRADA ALTA TENSAO'),
      ('GRAXARIA','GRX-GER','GERACAO DE VAPOR','PAE20','PAINEL ELETRICO NA GRAXARIA'),
      ('GRAXARIA','GRX-GER','GERACAO DE VAPOR','PAEGRX','PAINEL ELETRICO NA GRAXARIA')
  ) as t(endereco, local, equipamento, tag_interna, descricao_detalhada)
)
insert into public.assets (tag, name, description, site_id, tenant_id)
select
  s.tag_interna,
  s.equipamento,
  s.descricao_detalhada,
  si.id,
  '00000000-0000-0000-0000-000000000000'::uuid
from source s
join public.sites si
  on si.tenant_id = '00000000-0000-0000-0000-000000000000'::uuid
 and si.name = s.local
 and coalesce(si.address, '') = s.endereco
where not exists (
  select 1
  from public.assets a
  where a.tenant_id = '00000000-0000-0000-0000-000000000000'::uuid
    and a.tag = s.tag_interna
);
